security {
    authentication-key-chains {
        key-chain JNCIE {
            key 0 {
                secret "$9$NzVs4Pfz6/tUjmTzF/9evMXdb";
                start-time "2024-1-1.00:01:00 +0000";
                algorithm ao;
                ao-attribute {
                    send-id 2;
                    recv-id 1;
                    tcp-ao-option enabled;
                    cryptographic-algorithm aes-128-cmac-96;
                }
            }
        }
    }
}
routing-options {
    rib inet6.3 {
        static {
            route 0:0:0:0:0:ffff::/96 receive;
        }
    }
    autonomous-system 54000;
}
protocols {
    bgp {
        group cluster-1 {
            type internal;
            local-address 172.16.0.10;
            family inet {
                unicast;
            }
            family inet6 {
                labeled-unicast {
                    explicit-null;
                }
            }
            authentication-algorithm ao;
            authentication-key-chain JNCIE;
            cluster 0.0.0.1;
            bfd-liveness-detection {
                minimum-interval 3000;
            }
            neighbor 172.16.0.1;
            neighbor 172.16.0.6;
            neighbor 172.16.0.7;
            neighbor 172.16.0.8;
        }
        group cluster-2 {
            type internal;
            local-address 172.16.0.10;
            family inet {
                unicast;
            }
            family inet6 {
                labeled-unicast {
                    explicit-null;
                }
            }
            authentication-algorithm ao;
            authentication-key-chain JNCIE;
            cluster 0.0.0.2;
            bfd-liveness-detection {
                minimum-interval 3000;
            }
            neighbor 172.16.0.2;
            neighbor 172.16.0.3;
            neighbor 172.16.0.4;
            neighbor 172.16.0.5;
        }
        disable-4byte-as;
    }
    isis {
        interface all {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 2000;
                    multiplier 3;
                }
            }
        }
        level 2 disable;
        level 1 {
            authentication-key "$9$km5FIRSeK8Ct1h"; ## SECRET-DATA
            authentication-type md5;
        }
    }
}