## Junos Lab ##
version 23.4R2-S2.1;
system {
    host-name vpe1;
    root-authentication {
        encrypted-password "$6$xy3FzJmi$HqEFdl7cLWakDR9MXSXs4Q5wHvM7mLVNJ23/Z5u2WwojI48Vo4/FRtgKcKbZ612fVePtL/F9ntMTUfV/i0OPi/";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$2aC.n6Cp$cFnTfvno/Teq17voNja8uzOk/f6xkZherrPR1h8XfYpfqggrUwcwSxbRZwuKyJ0xQ/D7QUTdeDkhi5aF0Dgnv/";
            }
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
    management-instance;
    static-host-mapping {
        srv1 inet 172.16.0.1;
        vpe2 inet 10.0.0.2;
    }
    ntp {
        server 192.168.121.101 routing-instance mgmt_junos;
    }
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 12;
        }
    }
}
interfaces {
    ge-0/0/0 {
        mtu 1514;
        unit 0 {
            description "vpe1 -> vpe2";
            family inet {
                address 172.20.0.1/30;
            }
            family inet6 {
                address 2001:db8:1000::1/64;
            }
        }
    }
    ge-0/0/1 {
        mtu 1514;
        unit 0 {
            description "vpe1 -> srv1 [stub]";
            family inet {
                address 172.16.0.3/24;
            }
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.121.103/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                filter {
                    input protect_re;
                }
                address 10.0.0.3/32;
            }
        }
    }
}
firewall {
    family inet {
        filter protect_re {
            term tcp_estab {
                from {
                    tcp-established;
                }
                then accept;
            }
            term allow_telnet_ssh {
                from {
                    protocol tcp;
                    port [ ssh telnet ];
                }
                then {
                    log;
                    accept;
                }
            }
            term allow_ntp {
                from {
                    source-address {
                        10.0.0.3/32;
                        192.168.121.101/32;
                    }
                    protocol udp;
                    port ntp;
                }
                then {
                    log;
                    accept;
                }
            }
            term discard_all {
                then {
                    log;
                    discard;
                }
            }
        }
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            static {
                route 0.0.0.0/0 next-hop 192.168.121.1;
            }
        }
    }
}
protocols {
    router-advertisement {
        interface ge-0/0/0.0;
    }
    lldp {
        interface fxp0 {
            disable;
        }
        interface all;
    }
}
