## Last changed: 2026-06-14 21:03:27 UTC
version 23.2R2.21;
system {
    host-name vce2-5;
    root-authentication {
        encrypted-password "$6$i05YzKFY$yKSch2Qj1xWytwWjQ5lf7CAdXimrGmqf63RaBeYeNw229OIPVKoEWlQH7iSryNLVPLYrQybT.8OnWQm7.eOMB1";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$lLqGIEQd$oow1SEzE0R6LsIRclu1kUMcnOQy7H5XrfdRPKLy7YKjFHZiJu8KWUiwHPQMtq9OMDrr0RvC7DATx1beEBFe9g/";
            }
        }
    }
    services {
        ssh;
        extension-service {
            request-response {
                grpc {
                    clear-text {
                        port 57400;
                    }
                    max-connections 4;
                }
            }
        }
        netconf {
            ssh;
            rfc-compliant;
        }
    }
    management-instance;
    static-host-mapping {
        vr1 inet 172.16.0.1;
        vr2 inet 172.16.0.2;
        vr3 inet 172.16.0.3;
        vr4 inet 172.16.0.4;
        vr5 inet 172.16.0.5;
        vr6 inet 172.16.0.6;
        vr7 inet 172.16.0.7;
        vr8 inet 172.16.0.8;
        vr10 inet 172.16.0.10;
        vdc2 inet 172.16.0.12;
        vdc3 inet 172.16.0.13;
        vix1 inet 172.16.0.21;
        vix2 inet 172.16.0.22;
        vce1-1 inet 172.16.0.111;
        vce1-2 inet 172.16.0.112;
        vce1-3 inet 172.16.0.113;
        vce1-4 inet 172.16.0.114;
        vce2-1 inet 172.16.0.121;
        vce2-2 inet 172.16.0.122;
        vce2-3 inet 172.16.0.123;
        vce2-4 inet 172.16.0.124;
        vce3-1 inet 172.16.0.131;
        vce3-2 inet 172.16.0.132;
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 96;
        }
    }
}
interfaces {
    ge-0/0/5 {
        description vce2-5->vr7;
        flexible-vlan-tagging;
        unit 323 {
            description vce2-5->vr7;
            vlan-id 323;
            family inet {
                address 192.168.1.5/24;
            }
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 10.0.0.15/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 172.16.0.125/32;
            }
        }
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            static {
                route 0.0.0.0/0 next-hop 10.0.0.2;
            }
        }
        description management-instance;
    }
}
protocols {
    lldp {
        interface fxp0 {
            disable;
        }
        interface all;
    }
}
