version 23.2R2.21;
system {
    host-name vce2-3;
    root-authentication {
        encrypted-password "$6$EVOTZ6ZW$K9cX7Brc.zm2BI91IxPCg.58nsaM5maO1aTOsab9rqgAKH49K03FyXsxAN3ZVeJlydNNCHyQDLuwUrj1xGUWb/";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$/DHcDDqh$Kqsn3YWaHC8/ZoQ2f9nF82bcfEoIH93uHHKtBrpPbpQIIXzxUURg6yKhbXkSKMLZskmhAVDaQkf2PN8XoCaku1";
            }
        }
    }
    services {
        ssh;
        extension-service {
            request-response {
                grpc {
                    clear-text {
                        port 57400;
                    }
                    max-connections 4;
                }
            }
        }
        netconf {
            ssh;
            rfc-compliant;
        }
    }
    management-instance;
    static-host-mapping {
        vr1 inet 172.16.0.1;
        vr2 inet 172.16.0.2;
        vr3 inet 172.16.0.3;
        vr4 inet 172.16.0.4;
        vr5 inet 172.16.0.5;
        vr6 inet 172.16.0.6;
        vr7 inet 172.16.0.7;
        vr8 inet 172.16.0.8;
        vr10 inet 172.16.0.10;
        vdc2 inet 172.16.0.12;
        vdc3 inet 172.16.0.13;
        vix1 inet 172.16.0.21;
        vix2 inet 172.16.0.22;
        vce1-1 inet 172.16.0.111;
        vce1-2 inet 172.16.0.112;
        vce1-3 inet 172.16.0.113;
        vce1-4 inet 172.16.0.114;
        vce2-1 inet 172.16.0.121;
        vce2-2 inet 172.16.0.122;
        vce2-4 inet 172.16.0.124;
        vce2-5 inet 172.16.0.125;
        vce3-1 inet 172.16.0.131;
        vce3-2 inet 172.16.0.132;
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 96;
        }
    }
}
interfaces {
    ge-0/0/5 {
        flexible-vlan-tagging;
        unit 0 {
            description vce2-3->vr4;
            vlan-id 4093;
        }
        unit 320 {
            description "vce2-3 -> vr4";
            vlan-id 320;
            family inet {
                address 192.168.0.78/30;
            }
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 10.0.0.15/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 172.16.0.123/32;
            }
        }
    }
}
policy-options {
    policy-statement EXPORT_LO {
        term 1 {
            from {
                protocol direct;
                route-filter 172.16.0.123/32 exact;
            }
            then accept;
        }
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            static {
                route 0.0.0.0/0 next-hop 10.0.0.2;
            }
        }
        description management-instance;
    }
}
routing-options {
    autonomous-system 64600;
}
protocols {
    bgp {
        group pe {
            type external;
            export EXPORT_LO;
            peer-as 54001;
            neighbor 192.168.0.77;
        }
    }
    lldp {
        interface fxp0 {
            disable;
        }
        interface all;
    }
}
