## Junos Lab ##
version 23.4R2-S2.1;
system {
    host-name vpe1;
    root-authentication {
        encrypted-password "$6$NNUAn6mI$3PJiB4B.xspcOEiop7ejgyokolNykKIakNErA7Zggmot/KVvKeJkv9/frrggChjrxdefn6gT83i/PF1lrLv2n0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$anZRsv.T$l5NqmBug6xbvL3X/kv/UBz2v/lmTmnKTIbl4faYhijhBIp/Nc/mH/yyrMB8u.hrYLRmINlaTDiLyet76m7Lm40";
            }
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
    ntp {
        server 192.168.99.101 routing-instance mgmt_junos;
    }
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 12;
        }
    }
event-options {
    generate-event {
        every_1m time-interval 60;
    }
    policy log_core_file_warning {
        events every_1m;
        then {
            event-script log-core-file-warning.slax;
        }
    }
    event-script {
        traceoptions {
            file event.log;
            flag all;
        }
        file log-core-file-warning.slax;
    }
}
