## Junos Lab ##
system {
    host-name route-reflector;
}
routing-options {
    rib inet6.3 {
        static {
            route 0:0:0:0:0:ffff::/96 receive;
        }
    }
    autonomous-system 54000;
}
security {
    authentication-key-chains {
        key-chain JNCIE {
            key 0 {
                secret "$9$JDUi.AtOREyQFCuOBEhVws4GD"; ## Junos Lab ## SECRET-DATA
                start-time "2026-6-14.06:06:00 +0000";
                algorithm ao;
                ao-attribute {
                    send-id 1;
                    recv-id 1;
                    tcp-ao-option enabled;
                    cryptographic-algorithm aes-128-cmac-96;
                }
            }
        }
    }
}
protocols {
    bgp {
        group cluster-1 {
            type internal;
            local-address 172.16.0.10;
            family inet {
                unicast;
            }
            family inet6 {
                labeled-unicast {
                    explicit-null;
                }
            }
            authentication-key "$9$WA/XNbiHmTQn4ajq"; ## Junos Lab ## SECRET-DATA
            cluster 0.0.0.1;
            bfd-liveness-detection {
                minimum-interval 3000;
            }
            neighbor 172.16.0.1;
            neighbor 172.16.0.6;
            neighbor 172.16.0.7;
            neighbor 172.16.0.8;
        }
        group cluster-2 {
            type internal;
            local-address 172.16.0.10;
            family inet {
                unicast;
            }
            family inet6 {
                labeled-unicast {
                    explicit-null;
                }
            }
            authentication-key "$9$WA/XNbiHmTQn4ajq"; ## Junos Lab ## SECRET-DATA
            cluster 0.0.0.2;
            bfd-liveness-detection {
                minimum-interval 3000;
            }
            neighbor 172.16.0.2;
            neighbor 172.16.0.3;
        }
        disable-4byte-as;
    }
    isis {
        interface all {
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 2000;
                    multiplier 3;
                }
            }
        }
        level 2 disable;
        level 1 {
            authentication-key "$9$lw6v87ZGi.mTwYJD";
            authentication-type md5;
            wide-metrics-only;
        }
    }
}
interfaces {
    ge-0/0/8 {
        flexible-vlan-tagging;
        unit 0 {
            description vR10->vR1;
            vlan-id 4093;
        }
        unit 206 {
            description "vr10 -> vr1";
            vlan-id 206;
            family inet {
                address 172.20.0.65/31;
            }
            family iso;
        }
    }
    ge-0/0/9 {
        flexible-vlan-tagging;
        unit 0 {
            description vR10->vR2;
            vlan-id 4093;
        }
        unit 207 {
            description "vr10 -> vr2";
            vlan-id 207;
            family inet {
                address 172.20.0.67/31;
            }
            family iso;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 172.16.0.10/32;
            }
            family iso {
                address 49.0001.0000.0000.0010.00;
            }
            family inet6 {
                address fd00:172:16::172:16:1:0/128;
            }
        }
    }
}